version: "3.8"
services:
  tcoop-redis:
    container_name: tcoop-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: moonsungkim/tcoop-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    platform: linux/amd64
    ports:
      - "6379:6379"
  tcoop-database:
    container_name: tcoop-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: moonsungkim/tcoop-database
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=tcoop
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
  tcoop-app:
    container_name: tcoop-app
    build: .
    depends_on:
      - tcoop-database
      - tcoop-redis
    image: moonsungkim/tcoop-app
    environment:
      - MYSQL_DATABASE=tcoop
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "80:8080"
    restart: always